version: '3.1'

services:
  db:
    image: mysql:8.0.35
    volumes:
      - dbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dnd5e_character-forge_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80

  spring-api:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dnd5e_character-forge_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
    #restart: on-failure

volumes:
  dbase: